font_family      family='JetBrains Mono' style='Thin'
bold_font        family='JetBrains Mono' style='Bold'
italic_font      family='JetBrains Mono' style='Thin Italic'
bold_italic_font family='JetBrains Mono' style='Bold Italic'

font_size 14.0

disable_ligatures always

modify_font underline_position 2
modify_font cell_height 2px

undercurl_style thick-sparse

url_style double

enable_audio_bell no

placement_strategy top

hide_window_decorations yes

tab_bar_edge top
tab_bar_margin_height 0.0 1.0
tab_bar_style powerline
tab_title_template "  {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}  "
active_tab_title_template "  {fmt.bold}{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}{fmt.nobold}  "
inactive_tab_font_style italic

# Needed by `color` (~/.zsh/color.zsh) to recolor running windows via `kitten @ set-colors`.
allow_remote_control socket-only
listen_on unix:~/.config/kitty/kitty.sock

shell_integration disabled

# Default color scheme.
include themes/base16-default-dark.conf

# Written by `color`; kitty ignores it if not present.
include colors.conf
